# Default values for django-todo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Pod replicas count
##
replicas: 1

## django-todo admin user credentials (created once on chart install)
#
adminUser: {}
  # login: admin
  # email: admin@example.com
  # password: t0d0Adm1n

## Postgres database connectivity parameters
##
database:
  host: postgres
  port: "5432"
  username: postgres
  password: postgres
  dbName: todo

backend:
  image:
    repository: torbik/django-todo
    tag: 0.0.1
    pullPolicy: IfNotPresent

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 256Mi
    # requests:
    #   cpu: 50m
    #   memory: 64Mi

nginx:
  image:
    repository: nginx
    tag: 1.17.8-alpine
    pullPolicy: IfNotPresent

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 256Mi
    # requests:
    #   cpu: 50m
    #   memory: 64Mi

## updateStrategy for deployment
updateStrategy:
  type: RollingUpdate

service:
  type: ClusterIP
  port: 8080

livenessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 2
  periodSeconds: 30
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 10
  failureThreshold: 3
  successThreshold: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

tolerations: []

affinity: {}
  # podAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #   - labelSelector:
  #         matchLabels:
  #           component: portal
  #     topologyKey: kubernetes.io/hostname
  #   preferredDuringSchedulingIgnoredDuringExecution:
  #   - weight: 100
  #     podAffinityTerm:
  #       labelSelector:
  #         matchLabels:
  #           component: portal
  #       topologyKey: failure-domain.beta.kubernetes.io/zone

# Specifies maxUnavailable settings for Pod Disruption Budget
maxUnavailable: 1

test:
  enabled: true
  image:
    repository: unguiculus/docker-python3-phantomjs-selenium
    tag: v1
    pullPolicy: IfNotPresent
  securityContext:
    fsGroup: 1000
  containerSecurityContext:
    runAsUser: 1000
    runAsNonRoot: true
