apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-todo.fullname" . }}-nginx
  labels:
    {{- include "django-todo.labels" . | nindent 4 }}
    subcomponent: nginx
data:
  nginx.conf: |
{{ .Files.Get "conf/nginx.conf" | indent 4 }}
