apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-todo.fullname" . }}-db
  labels:
    {{- include "django-todo.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
type: Opaque
data:
  dbPassword: {{ .Values.database.password | b64enc | quote }}
