apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-todo.fullname" . }}-hook
  labels:
    {{- include "django-todo.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
type: Opaque
data:
  adminPassword: {{ .Values.adminUser.password | b64enc | quote }}
